env:
  global:
    - secure: hXwhJvtXk9ouSE4YGB9Hy0LicPvXAhDrpb4H0+l/T6DL2jqZXujxvucPfgbhbQ8/qwGn6wsQt7LvYKF1eTA5pEIGPJTeJBY/DhE/38O6tj9kA3/xuQLPrZBVCCB3P+R9iGEc1R6AQQ4Mbiz/Nt0dzThIyo65r+JfFVacYdqhKZc=

before_script:
  - git config --global user.email "jaeyoung@monodiary.net"
  - git config --global user.name "Travis"

script:
  - git clone --depth 5 --quiet https://${GH_TOKEN}@github.com/Software-Maestro/__static-creator.git creator

after_success:
  - cd creator
  - git commit -m "Renew site contents" --allow-empty
  - git push https://${GH_TOKEN}@github.com/Software-Maestro/__static-creator.git master --quiet

branches:
  only:
    - master
